apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-test-deploy-app-run
spec:
  pipelineRef:
    name: build-test-deploy-app
  resources:
  - name: git
    resourceRef:
      name: example-github
  - name: image
    resourceRef:
      name: example-image